spring.application.name=notSpot

#temp db code to change later

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/notSpot
spring.datasource.username=music
spring.datasource.password=music
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL (optional, useful for dev)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
