spring.application.name=notSpot
server.port=${SERVER_PORT:8080}

# Database connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notSpot}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:music}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:music}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Show SQL (optional, useful for dev)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File uploads
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:25MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:25MB}
app.song-storage.dir=${SONG_STORAGE_DIR:${user.dir}/uploads/songs}
